setwd("C:/Users/Abhinav Vijayakumar/Desktop/VIT Academics/Sem 6/Essentials of Data Analytics/LAB/LAB 3")
dff=read.csv("weatherHistory2016.csv")
head(dff)
library(dplyr)
library(GGally)
a=sample_n(dff,200)
head(a)
cor.test(a$Temperature..C.,a$Apparent.Temperature..C.)
cor.test(a$Temperature..C.,a$Humidity)
cor.test(a$Temperature..C.,a$Wind.Speed..km.h.)
cor.test(a$Temperature..C.,a$Wind.Bearing..degrees.)
cor.test(a$Temperature..C.,a$Pressure..millibars.)
cor.test(a$Temperature..C.,a$Visibility..km.)
cor.test(a$Temperature..C.,a$Loud.Cover)
ggcorr(a %>% mutate_if(is.factor, as.numeric), label = TRUE)
lmodel=lm(a$Temperature..C.~a$Apparent.Temperature..C.+a$Humidity+a$Visibility..km.)
summary(lmodel)
plot(lmodel)
